apiVersion: v1
kind: Service
metadata:
  name: mcf-extproc-service
  namespace: istio-system
spec:
  selector:
    app: mcf-extproc
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcf-extproc
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcf-extproc
  template:
    metadata:
      labels:
        app: mcf-extproc
      # annotations:
      #   sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: mcf-extproc
          # Built from Dockerfile: docker build -t mcf-extproc-server:latest .
          # Load onto kind cluster: kind load docker-image mcf-extproc-server:latest --name mcp-gateway
          image: mcf-extproc-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50053
