# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udpa/core/v1/collection_entry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'udpa/core/v1/collection_entry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from udpa.core.v1 import resource_locator_pb2 as udpa_dot_core_dot_v1_dot_resource__locator__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#udpa/core/v1/collection_entry.proto\x12\x0cudpa.core.v1\x1a\x19google/protobuf/any.proto\x1a\x1dudpa/annotations/status.proto\x1a#udpa/core/v1/resource_locator.proto\x1a\x17validate/validate.proto\"\x95\x02\n\x0f\x43ollectionEntry\x12\x30\n\x07locator\x18\x01 \x01(\x0b\x32\x1d.udpa.core.v1.ResourceLocatorH\x00\x12\x41\n\x0cinline_entry\x18\x02 \x01(\x0b\x32).udpa.core.v1.CollectionEntry.InlineEntryH\x00\x1ar\n\x0bInlineEntry\x12*\n\x04name\x18\x01 \x01(\tB\x1c\xfa\x42\x19r\x17\x32\x15^[0-9a-zA-Z_\\-\\.~:]+$\x12\x0f\n\x07version\x18\x02 \x01(\t\x12&\n\x08resource\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB\x19\n\x12resource_specifier\x12\x03\xf8\x42\x01\x42>\n\x1c\x63om.github.udpa.udpa.core.v1B\x14\x43ollectionEntryProtoP\x01\xba\x80\xc8\xd1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udpa.core.v1.collection_entry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.github.udpa.udpa.core.v1B\024CollectionEntryProtoP\001\272\200\310\321\006\002\010\001'
  _globals['_COLLECTIONENTRY_INLINEENTRY'].fields_by_name['name']._loaded_options = None
  _globals['_COLLECTIONENTRY_INLINEENTRY'].fields_by_name['name']._serialized_options = b'\372B\031r\0272\025^[0-9a-zA-Z_\\-\\.~:]+$'
  _globals['_COLLECTIONENTRY'].oneofs_by_name['resource_specifier']._loaded_options = None
  _globals['_COLLECTIONENTRY'].oneofs_by_name['resource_specifier']._serialized_options = b'\370B\001'
  _globals['_COLLECTIONENTRY']._serialized_start=174
  _globals['_COLLECTIONENTRY']._serialized_end=451
  _globals['_COLLECTIONENTRY_INLINEENTRY']._serialized_start=310
  _globals['_COLLECTIONENTRY_INLINEENTRY']._serialized_end=424
# @@protoc_insertion_point(module_scope)
