# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udpa/core/v1/context_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'udpa/core/v1/context_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!udpa/core/v1/context_params.proto\x12\x0cudpa.core.v1\x1a\x1dudpa/annotations/status.proto\"w\n\rContextParams\x12\x37\n\x06params\x18\x01 \x03(\x0b\x32\'.udpa.core.v1.ContextParams.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42<\n\x1c\x63om.github.udpa.udpa.core.v1B\x12\x43ontextParamsProtoP\x01\xba\x80\xc8\xd1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udpa.core.v1.context_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.github.udpa.udpa.core.v1B\022ContextParamsProtoP\001\272\200\310\321\006\002\010\001'
  _globals['_CONTEXTPARAMS_PARAMSENTRY']._loaded_options = None
  _globals['_CONTEXTPARAMS_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXTPARAMS']._serialized_start=82
  _globals['_CONTEXTPARAMS']._serialized_end=201
  _globals['_CONTEXTPARAMS_PARAMSENTRY']._serialized_start=156
  _globals['_CONTEXTPARAMS_PARAMSENTRY']._serialized_end=201
# @@protoc_insertion_point(module_scope)
