# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udpa/core/v1/resource.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'udpa/core/v1/resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from udpa.core.v1 import resource_name_pb2 as udpa_dot_core_dot_v1_dot_resource__name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1budpa/core/v1/resource.proto\x12\x0cudpa.core.v1\x1a\x19google/protobuf/any.proto\x1a\x1dudpa/annotations/status.proto\x1a udpa/core/v1/resource_name.proto\"m\n\x08Resource\x12(\n\x04name\x18\x01 \x01(\x0b\x32\x1a.udpa.core.v1.ResourceName\x12\x0f\n\x07version\x18\x02 \x01(\t\x12&\n\x08resource\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB7\n\x1c\x63om.github.udpa.udpa.core.v1B\rResourceProtoP\x01\xba\x80\xc8\xd1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udpa.core.v1.resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.github.udpa.udpa.core.v1B\rResourceProtoP\001\272\200\310\321\006\002\010\001'
  _globals['_RESOURCE']._serialized_start=137
  _globals['_RESOURCE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
