# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udpa/core/v1/resource_name.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'udpa/core/v1/resource_name.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from udpa.core.v1 import context_params_pb2 as udpa_dot_core_dot_v1_dot_context__params__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n udpa/core/v1/resource_name.proto\x12\x0cudpa.core.v1\x1a\x1dudpa/annotations/status.proto\x1a!udpa/core/v1/context_params.proto\x1a\x17validate/validate.proto\"\x85\x01\n\x0cResourceName\x12\x14\n\x02id\x18\x01 \x03(\tB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12\x11\n\tauthority\x18\x02 \x01(\t\x12\x1e\n\rresource_type\x18\x03 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12,\n\x07\x63ontext\x18\x04 \x01(\x0b\x32\x1b.udpa.core.v1.ContextParamsB;\n\x1c\x63om.github.udpa.udpa.core.v1B\x11ResourceNameProtoP\x01\xba\x80\xc8\xd1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udpa.core.v1.resource_name_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.github.udpa.udpa.core.v1B\021ResourceNameProtoP\001\272\200\310\321\006\002\010\001'
  _globals['_RESOURCENAME'].fields_by_name['id']._loaded_options = None
  _globals['_RESOURCENAME'].fields_by_name['id']._serialized_options = b'\372B\005\222\001\002\010\001'
  _globals['_RESOURCENAME'].fields_by_name['resource_type']._loaded_options = None
  _globals['_RESOURCENAME'].fields_by_name['resource_type']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_RESOURCENAME']._serialized_start=142
  _globals['_RESOURCENAME']._serialized_end=275
# @@protoc_insertion_point(module_scope)
